DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS director;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE director (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE movie (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  director INTEGER NOT NULL,
  added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  added_by INTEGER NOT NULL,
  title TEXT UNIQUE NOT NULL,
  year TEXT NOT NULL,
  FOREIGN KEY (added_by) REFERENCES user (id),
  FOREIGN KEY (director) REFERENCES director (id)
);